//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurumsalProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSMGRBCEGEN002
    {
        public string COMCODE { get; set; }
        public string LANCODE { get; set; }
        public string LANTEXT { get; set; }
    }
}
