//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurumsalProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSMGRBCEBOMHEAD
    {
        public string COMCODE { get; set; }
        public string BOMDOCTYPE { get; set; }
        public string BOMDOCNUM { get; set; }
        public System.DateTime BOMDOCFROM { get; set; }
        public System.DateTime BOMDOCUNTIL { get; set; }
        public string MATDOCTYPE { get; set; }
        public string MATDOCNUM { get; set; }
        public decimal QUANTITY { get; set; }
        public Nullable<int> ISDELETED { get; set; }
        public Nullable<int> ISPASSIVE { get; set; }
        public string DRAWNUM { get; set; }
    
        public virtual BSMGRBCEBOMCONTENT BSMGRBCEBOMCONTENT { get; set; }
    }
}
