//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurumsalProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSMGRBCEROTHEAD
    {
        public string COMCODE { get; set; }
        public string ROTDOCTYPE { get; set; }
        public string ROTDOCNUM { get; set; }
        public System.DateTime ROTDOCFROM { get; set; }
        public System.DateTime ROTDOCUNTIL { get; set; }
        public string MATDOCTYPE { get; set; }
        public string MATDOCNUM { get; set; }
        public decimal QUANTITY { get; set; }
        public Nullable<int> ISDELETED { get; set; }
        public Nullable<int> ISPASSIVE { get; set; }
        public string DRAWNUM { get; set; }
    
        public virtual BSMGRBCEROTBOMCONTENT BSMGRBCEROTBOMCONTENT { get; set; }
        public virtual BSMGRBCEROTOPRCONTENT BSMGRBCEROTOPRCONTENT { get; set; }
    }
}
