//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurumsalProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSMGRBCEROTOPRCONTENT
    {
        public string COMCODE { get; set; }
        public string ROTDOCTYPE { get; set; }
        public string ROTDOCNUM { get; set; }
        public System.DateTime ROTDOCFROM { get; set; }
        public System.DateTime ROTDOCUNTIL { get; set; }
        public string MATDOCTYPE { get; set; }
        public string MATDOCNUM { get; set; }
        public int OPRNUM { get; set; }
        public string WCMDOCTYPE { get; set; }
        public string WCMDOCNUM { get; set; }
        public string OPRDOCTYPE { get; set; }
        public Nullable<decimal> SETUPTIME { get; set; }
        public Nullable<decimal> MACHINETIME { get; set; }
        public Nullable<decimal> LABOURTIME { get; set; }
    
        public virtual BSMGRBCEROTHEAD BSMGRBCEROTHEAD { get; set; }
    }
}
