//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurumsalProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSMGRBCEWCMHEAD
    {
        public string COMCODE { get; set; }
        public string WCMDOCTYPE { get; set; }
        public string WCMDOCNUM { get; set; }
        public System.DateTime WCMDOCFROM { get; set; }
        public System.DateTime WCMDOCUNTIL { get; set; }
        public string MAINWCMDOCTYPE { get; set; }
        public string MAINWCMDOCNUM { get; set; }
        public string CCMDOCTYPE { get; set; }
        public string CCMDOCNUM { get; set; }
        public Nullable<decimal> WORKTIME { get; set; }
        public Nullable<int> ISDELETED { get; set; }
        public Nullable<int> ISPASSIVE { get; set; }
    
        public virtual BSMGRBCEWCMOPR BSMGRBCEWCMOPR { get; set; }
        public virtual BSMGRBCEWCMTEXT BSMGRBCEWCMTEXT { get; set; }
    }
}
