//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurumsalProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSMGRBCEMATTEXT
    {
        public string COMCODE { get; set; }
        public string MATDOCTYPE { get; set; }
        public string MATDOCNUM { get; set; }
        public System.DateTime MATDOCFROM { get; set; }
        public System.DateTime MATDOCUNTIL { get; set; }
        public string LANCODE { get; set; }
        public string MATSTEXT { get; set; }
        public string MATLTEXT { get; set; }
    
        public virtual BSMGRBCEMATHEAD BSMGRBCEMATHEAD { get; set; }
    }
}
