//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurumsalProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSMGRBCECCMHEAD
    {
        public string COMCODE { get; set; }
        public string CCMDOCTYPE { get; set; }
        public string CCMDOCNUM { get; set; }
        public System.DateTime CCMDOCFROM { get; set; }
        public System.DateTime CCMDOCUNTIL { get; set; }
        public string MAINCCMDOCTYPE { get; set; }
        public string MAINCCMDOCNUM { get; set; }
        public Nullable<int> ISDELETED { get; set; }
        public Nullable<int> ISPASSIVE { get; set; }
    
        public virtual BSMGRBCECCMTEXT BSMGRBCECCMTEXT { get; set; }
    }
}
